### ISSUE TITLE
Add stashnotifier-plugin to plugins.txt

### ISSUE THREAD

**Issue by danielezer** [odavid/my-bloody-jenkins#141]
I think you should add the bitbucket notifier plugin to the base plugins

**Comment by odavid** [comment]
https://github.com/jenkinsci/stashnotifier-plugin

**Comment by danielezer** [comment]
@odavid is this available as the helm chart?

**Comment by odavid** [comment]
@danielezer  - the build started, however, for some reason, travis builds are getting stuck and failed, and need manual restarts (sometimes 5 times) before they are finished successfully  ):, 
Once the build will finish (Hopefully today), then it is pushed as <latest>  to docker hub.
