### ISSUE TITLE
downgrade git plugin

### ISSUE THREAD

**Issue by danielezer** [odavid/my-bloody-jenkins#142]
A bug in the git plugin causes the stash-notifier plugin to not work properly.
According to this issue - https://github.com/jenkinsci/stashnotifier-plugin/issues/219, downgrading the git to 3.9.1 would solve this issue. WDTY? @odavid

**Comment by odavid** [comment]
@danielezer - I want to avoid downgrading plugins within the image. I will wait for the plugin owners to finish their job
But, you can use `JENKINS_ENV_PLUGINS` variable to specify the right versions.
A word of caution: You will need to make sure that nothing is broken with plugin dependencies, so you might need to downgrade other plugins as well. 

Hope it helps

**Comment by danielezer** [comment]
Thanks, fair enough. I’ll close the issue
