### ISSUE TITLE
Docker inside has stopped working due to plugins upgrade

### ISSUE THREAD

**Issue by matankatz** [odavid/my-bloody-jenkins#147]
On the latest LTS image (2.190.1) "durable-task" plugin was upgraded to 1.31.
This plugin is breaking the use of "docker.inside" (https://issues.jenkins-ci.org/browse/JENKINS-59903).
According to the issue reverting to 1.30 fixed the problem.

**Comment by matankatz** [comment]
It seems like the plugin installed is still version 1.31.
![image](https://user-images.githubusercontent.com/9637720/67640089-703ef080-f900-11e9-8688-ed790790bd5d.png)

**Comment by odavid** [comment]
Plugins are persistent. Delete the plugin from the plugins directory and restart

**Comment by matankatz** [comment]
Thanks for the help.
As usual, amazing with the fast response. :)
