### ISSUE TITLE
Support Kubernetes "Max connections to Kubernetes API" in cloud config

### ISSUE THREAD

**Issue by matankatz** [odavid/my-bloody-jenkins#179]
We keep encounter issue where we are running out of connections to K8s cluster.
It can be handled using "Max connections to Kubernetes API" in Cloud configuration.

We are using the helm deployment of MBJ.
Can it be configured using the cloud configuration?

**Comment by odavid** [comment]
Hi @matankatz - the field is called `maxRequestsPerHost` within the k8s cloud configuration.
It was already there, only was not in the readme file.
Updated the readme...

This is the field in k8s plugin - https://github.com/jenkinsci/kubernetes-plugin/blob/e83e51f80a9f9b66655977af5711e1af09687aed/src/main/resources/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud/config.jelly#L74
