### ISSUE TITLE
[Feature Request] Security: github-oauth authorisation strategy support

### ISSUE THREAD

**Issue by Sudokamikaze** [odavid/my-bloody-jenkins#184]
Hi,

I'd like to open a FR for github-oauth/gitlab-oauth authorisation strategy,
It could be implemented with the same as Google implemented, here you can find few snippets
https://plugins.jenkins.io/github-oauth/

I can implement it if you don't mind, but let's discuss before any further actions

Thank you!

**Comment by odavid** [comment]
Hi, 
Sorry for the late response...
Sure, I have no problem at all...
Just pay attention to:
* README
* Tests
* sorted plugins.txt

**Comment by Sudokamikaze** [comment]
Hi @odavid 
Sorry for late response as well :)

I've implemented it in https://github.com/odavid/my-bloody-jenkins/pull/189
Running tests right now, will post results in PR

Thank you :)

**Comment by Sudokamikaze** [comment]
Thanks for merging my patch!
