### ISSUE TITLE
Handle JNLP Agent protocols

### ISSUE THREAD

**Issue by odavid** [odavid/my-bloody-jenkins#28]
Added environment variable to configure with protocols are enabled

**Comment by mrahbar** [comment]
I ran into this and offering you my solution. I basically wanted to disable a set of protocols thus I added an environment variable _JENKINS_ENV_JNLP_KILL_SWITCH_ to get rid of them. And here is the code
```
    def jnlpKillSwitch = env['JENKINS_ENV_JNLP_KILL_SWITCH']
    if(jnlpKillSwitch) {
        // Disable jnlp
        instance.setSlaveAgentPort(-1);

        // Disable old Non-Encrypted protocols
        def protocols = instance.getAgentProtocols()
        println 'Agent protocols: '+protocols
        HashSet<String> newProtocols = new HashSet<>(protocols);
        newProtocols.removeAll(Arrays.asList(
                "JNLP3-connect", "JNLP2-connect", "JNLP-connect", "CLI-connect"
        ));
        instance.setAgentProtocols(newProtocols);
        instance.save()
    }
```

Of course the list of protocols can be made configurable too but it is a good start.

**Comment by odavid** [comment]
Hi, thanks for that.
The jnlp protocols can be disabled today. Forgot to document it right.
https://github.com/odavid/my-bloody-jenkins/blob/master/CHANGELOG.md#2891-7 
Basically:

```yaml
security:
  securityOptions:
    jnlpProtocols:
     - JNLP
     - JNLP2
     - JNLP3
     - JNLP4
```
By default only JNLP4 is enabled (starting from 2.89.1-7)

If you want to see all the security options available, you can take a look at: https://github.com/odavid/my-bloody-jenkins/blob/master/config-handlers/SecurityConfig.groovy#L105 

As for the slave agent port, I cannot disable that, since I am only supporting JNLP.

Hope it helps.

**Comment by mrahbar** [comment]
Great! I missed that one, thanks.
