### ISSUE TITLE
[K8S] support environment variable for Jenkins admin password 

### ISSUE THREAD

**Issue by hagzag** [odavid/my-bloody-jenkins#95]
I wanted this to become an ENV var which I can basically add to kubernetes via secret ...

**Comment by odavid** [comment]
Did you see https://github.com/odavid/my-bloody-jenkins#environment-variable-substitution-and-remove-master-env-vars ?
I added lately the ability to use ```${ENV_VAR}``` within the yaml file

**Comment by hagzag** [comment]
Very cool will test it shortly ;)
